projectId=stackshift-16e39
applicationId=1:933963918835:android:cc5d3f06c4094c190e7686
apiKey=AIzaSyBImgLVfL0RNBc3xeZQr0G8MKzzdRVJ4cg
storageBucket=stackshift-16e39.firebasestorage.app
gcmSenderId=933963918835
authDomain=stackshift-16e39.firebaseapp.com
databaseUrl=
gaTrackingId=
